### ISSUE TITLE
Download All Tracks button broken

### ISSUE THREAD

**Issue by cblevins321** [tranxuanthang/lrcget#101]
Download All Tracks doesn't queue any lyrics to download. It shows 0 Downloaded after I click on it. Happens on Tracks, Album, and Artist tab. 

Looking at the console, I see the error that I've screenshotted. This on an M2 MacBook Air. Individual item downloads work fine, but I'd rather just hit the Download All button and let it run for a while. 

<img width="1284" alt="Screenshot 2024-06-26 at 2 16 31 PM" src="https://github.com/tranxuanthang/lrcget/assets/173949128/60bf17d3-718e-4546-b9d8-216d1f82053b">

Let me know if I can provide any more info! Thanks!

**Comment by Icenova20** [comment]
Same issue. 

Windows 10

![image](https://github.com/tranxuanthang/lrcget/assets/15051986/c2aaebd2-be38-4718-a07d-5e36400dba1d)

**Comment by tranxuanthang** [comment]
This is similar to issue #81, I did attempt a fix by converting a recursion to `while` loop in https://github.com/tranxuanthang/lrcget/commit/0ec12966a521a40801a795c70e241be514b4dd22 and released it in v0.3.2. I haven't received a feedback so I assumed it was fixed.

Reading minified code is hard, I looked into the file `index.238aff05.js`, but failed to find where the problem is.

I think I will make a new release with source mapping enabled, then ask you two to reproduce it again.

**Comment by tranxuanthang** [comment]
I found where the problem is. It is because of the spread operator `...trackIds` at this location:

https://github.com/tranxuanthang/lrcget/blob/0dfb16ad170bf5c573fb37074294f79908157eac/src/composables/downloader.js#L60

Related stateoverflow question for anyone who want to know more: https://stackoverflow.com/a/63706516

I will fix this soon and create a new release shortly!

**Comment by tranxuanthang** [comment]
Version v0.4.0 is released, could you verify your problem to see if it is fixed? @cblevins321 @Icenova20

https://github.com/tranxuanthang/lrcget/releases/tag/0.4.0

**Comment by cblevins321** [comment]
@tranxuanthang  It's working for me now (on a different computer and I had to do these one-time steps, but otherwise good). Thanks!

https://github.com/tranxuanthang/lrcget/issues/86
