### ISSUE TITLE
Custom server address

### ISSUE THREAD

**Issue by fineless71** [tranxuanthang/lrcget#123]
Since the LRCLIB server is open-source now, it would be nice to have a way to change the server address in the GUI. This could make usage easier for those who prefer to keep it local and download the database for themselves.

**Comment by tranxuanthang** [comment]
I totally agree; LRCGET should have an option or section for choosing any LRCLIB-compatible server, not just lrclib.net.

Some refactoring is required because the lrclib.net URL is hard-coded in many parts of the codebase.

I'll make the necessary change as soon as I can, hopefully it will be there in the next release.

**Comment by tranxuanthang** [comment]
This is available as of commit 85a3b484fe2ca9ac38ef9f5a65600777e5bef978! For now it is just the URL input field in the Preferences section but more improvement will come soon!
