### ISSUE TITLE
Issues with embeded lyrics

### ISSUE THREAD

**Issue by mohebbielman** [tranxuanthang/lrcget#133]
The new feature that allows you to embed lyrics directly into a file is quite useful, but it also poses two problems: 

**1**. The app still saves LRC files.
**2**. The more significant issue: the app does not scan embedded lyrics of a music file. Consequently, if you delete LRC files after embedding the lyrics, the app will treat those files as if they have no lyrics.

Version: 0.5.0

**Comment by tranxuanthang** [comment]
This is by design. The embedded lyrics feature works only one way: it embeds the lyrics into the music files while still keeping the lyrics in LRC or TXT files.

The reasons for this are:

- The code would become more complex and hard to maintain.
- Converting embedded lyrics back to LRC format is not straightforward. For example, the SYLT tag in ID3v2.3 (for synchronized lyrics) is not simply a text field like you think, but a strict structured array of (timestamp, lyrics_string) data. It is not 1:1 with [LRC file format](https://en.wikipedia.org/wiki/LRC_(file_format)#Core_format).
- Keeping the LRC (or TXT) file is harmless and provides the widest support, such as for players that do not support reading lyrics embedded in music files.
