### ISSUE TITLE
Fails to load some songs in the directory

### ISSUE THREAD

**Issue by solidspartan** [tranxuanthang/lrcget#15]
Directory has 70 songs but only show 56 songs in app on windows 11

**Comment by tranxuanthang** [comment]
Sorry for late answer, could you identify the songs that are missing, and see if they have anything in common?

**Comment by ToniKielo** [comment]
Same issue here. I have about 800 songs and it stops after 20.

I have weird filenames that contain things like..
- ones that contain quotes (")
- ones that contain single quotes (')
- ones that contain korean (방탄소년단  eg. BTS)
- umlauts (ä, ö, ...)
- colons (:)
- ampersands (&)
- @
- questionmarks (?)

.. and this whole folder is loaded through a network share eg. \\serverx\foldery
Tried refreshing and removing & readding the folder, no effect.

Otherwise lyrics downloading works well for the 20 that were loaded.

Tech details: 
- lrcget version: 0.2.1 (latest when posting the message)
- OS: windows 10 pro 22H2 19045.3693 64bit

**Comment by tranxuanthang** [comment]
@ToniKielo the weird filenames should be alright as long as it follows Windows filename rules. But the network drive/folder might be problematic, I've never tested this. I'll look into it when I have some free time, but you can try to run `lrcget.exe` from terminal/cmd/powershell, the logs may provide insights into why those files cannot be loaded.

**Comment by ToniKielo** [comment]
Figured it out, my mp3 metadata is missing the album information, preventing those songs from being displayed.
When I added album metadata and refreshed, they appeared in the UI.
Album information doesn't seem to be needed for the lyrics match/search, so hopefully that restriction can be removed.

**Comment by tueksta** [comment]
> Figured it out, my mp3 metadata is missing the album information, preventing those songs from being displayed.

Thanks for the hint, will add bogus album info now to work on my files :D

**Comment by HoreaM** [comment]
> Sorry for late answer, could you identify the songs that are missing, and see if they have anything in common?

Sorry to reopen this issue, but I'm also facing similar problems. I just can't figure out what's wrong. I have the following album (screenshot from mp3tag):
![image](https://github.com/tranxuanthang/lrcget/assets/11351405/b63e1d18-eab6-4589-a7c6-01bc655cd409)
From the whole list, only the 3 marked tracks are loaded into LRCGET. I can't really figure it out, the tags seem to be all alright. Am I missing something? Thanks a lot!

**Comment by tranxuanthang** [comment]
I'm closing this since this is a really old issue, and newest version of LRCGET and `lofty` can probably gracefully handle this.
