### ISSUE TITLE
Gui fails to list mp3 files with two or more artists

### ISSUE THREAD

**Issue by Wilollow** [tranxuanthang/lrcget#60]
This issue has been described in other issues already, but the cause was not completely clear, so i thought it wise to open a specific issue. The problem is that certain music files are not recognised upon loading a certain directory. HoreaM suggested this might be due to those files having multiple artists listed in the metadata. I can confirm that this is the case, as there is an overwhelming correlation between the two.

some suggestions:
- Use only the first artist in the metadata
- Use the album artist instead
- Allow the 'artist' field to be populated by an array of artists, joining them into a string when neccesary

**Comment by tranxuanthang** [comment]
I think I can reproduce this, actually there are some songs from my library having this issue.

> this might be due to those files having multiple artists listed in the metadata

You are right, but this might be more complicated than this. I haven't look but I bet the difference between ID3v2.3 and ID3v2.4 is involved. From what I know, ID3v2.3 doesn't support multiple values, while ID3v2.4 supports multiple values separated by a NULL byte (multiple artists for example).

Not entirely related but this is a similar problem I faced in the past: https://github.com/polyfloyd/rust-id3/issues/103

**Comment by tranxuanthang** [comment]
After upgrading `lofty` to newest version in https://github.com/tranxuanthang/lrcget/commit/dcec6f566096fb0ffbb71e85da882096d1d50415, I can confirm all of my previously failing songs are correctly scanned. The problem might simply be faulty/poor-supported metadata and might not related to multiple artists at all.

If you can help me test this commit, it would be great, otherwise I will make a minor release soon.
