### ISSUE TITLE
[LRCLib] API docs don't seem to be accurate for publishing

### ISSUE THREAD

**Issue by iiPythonx** [tranxuanthang/lrcget#72]
Hi, I maintain [lrcup](https://github.com/iiPythonx/lrcup), a CLI for uploading to LRCLib but also acting as a general API wrapper.  
According to the LRCLib documentation, /api/publish takes:
![image](https://github.com/tranxuanthang/lrcget/assets/35084023/d15467ea-211e-4493-bde6-d6ea8fe121ed)

All of which I provide:
![image](https://github.com/tranxuanthang/lrcget/assets/35084023/7ea8d9f8-6f42-4494-b124-a3c35d8e70f8)

Trying to upload a track with both unsynced and synced, LRCLib returns a 201 however when searching every song I've uploaded was marked as instrumental:
![image](https://github.com/tranxuanthang/lrcget/assets/35084023/dcc75bce-c53e-466b-81ef-b3eba497385d)

This affects the API as well, /api/get returns null for both syncedLyrics and plainLyrics despite the fact that I uploaded them.  
I've also tried swapping syncedLyrics with synced_lyrics as the source code in this repository does, and it still gets marked as instrumental.

Additionally, around 2 weeks ago I was able to successfully upload without issues. My code has not changed and is [available here](https://github.com/iiPythonx/lrcup/blob/main/lrcup/controller.py).

Any help would be appreciated.  
Awesome project by the way.

**Comment by tranxuanthang** [comment]
I see, I recently deployed a new backend implemented in Rust (instead of Node) to lrclib.net. It is very new, and I admit I rushed the release a bit in order to address performance issues with lrclib, so there might be a bug in publish API.

I'm looking into this right now.

Also, the newer source code used by lrclib is available here: https://github.com/tranxuanthang/lrclib. In the future, if there are any problems related to lrclib, you can now open new issue at lrclib repo for easier tracking!

**Comment by tranxuanthang** [comment]
I think the problem lies in these two files:

- https://github.com/tranxuanthang/lrclib/blob/21db7271b49bb5c5dbcdc982d7277f43e207714b/server/src/routes/publish_lyrics.rs#L83
- https://github.com/iiPythonx/lrcup/blob/3fdef0daaa406cf8ccc56dff36f35017836d9f1a/lrcup/__main__.py#L46

When submitting new synced lyrics, my new API implementation expects both plain lyrics and synced lyrics to be included in the request. For instance, if you submit `syncedLyrics` but leave `plainLyrics` empty, it will be treated as if the song is instrumental.

However, I did say this in the API documentation:

```
If BOTH plain lyrics and synchronized lyrics are left empty, the track will be marked as instrumental.
```

It is actually correct in LRCLIB's old backend, but also not very good. Because in both old and new backend, there is no timestamp stripping logic to turn synced lyrics into plain lyrics. In LRCGET it is only done at client side:

https://github.com/tranxuanthang/lrcget/blob/b0ec8fb746c31d327dc127f979dc97b184f22d98/src/components/library/edit-lyrics/PublishLyrics.vue#L93

I'll try to fix this and also add timestamp stripping logic to API side to keep compatibility, but I'm afraid some of the submitted lyrics (that have synced lyrics but not plain lyrics) using `lrcup` have been lost during my recent database cleanup and schema migration (when the new Rust backend was deployed). I was not aware that there were submissions containing synced lyrics without plain lyrics.

**Comment by tranxuanthang** [comment]
This is hopefully fixed in this commit and is deployed:

https://github.com/tranxuanthang/lrclib/commit/728e540ed4402a6d7934124206fa30758860bc24

Could you test it again?

**Comment by iiPythonx** [comment]
> I was not aware that there were submissions containing synced lyrics without plain lyrics.
I was about to update lrcup to automatically convert synced lyrics into plain lyrics and submit both.

> Could you test it again?
Will do in a moment.

**Comment by iiPythonx** [comment]
Yep, that commit did indeed fix the issue (along with me sending plain lyrics along with the synced ones, not sure why I didn't already have that implemented). Thanks for looking into this.
