### ISSUE TITLE
README says NO Mac Apple Silicon support but it seems to be the reverse

### ISSUE THREAD

**Issue by paour** [tranxuanthang/lrcget#83]
I'm on an Intel Mac, downloaded the 0.3.2 DMG version, and it is ONLY ARM (Apple Silicon), not x86/amd64.

<img width="1067" alt="SCR-20240525-kgtf" src="https://github.com/tranxuanthang/lrcget/assets/90963/d1e5cf25-4355-4171-b89b-23690600062b">

**Comment by paour** [comment]
Creating the build with the provided command generates a working amd64 version. If you're unable to cross-compile, I can provide the build.

**Comment by Triple-Z** [comment]
<img width="1121" alt="image" src="https://github.com/tranxuanthang/lrcget/assets/16285716/2b298004-3f0c-4e68-a7a2-aafd082b57f9">

Same question, it seems that it won't build amd64 version for mac since the version 0.3.0.

**Comment by tranxuanthang** [comment]
Weird, in v0.3.0 it did build `LRCGET_0.3.0_x64.dmg`. I don't remember changing anything until commit https://github.com/tranxuanthang/lrcget/commit/155d53224c2005c3fdc2905252ea9e2efc814ee2. I'll try to build this commit to see if it can produce both aarch64 and amd64 builds.

Also, I don't test any macOS build and only provide them as-is, because I don't have any Mac devices. If someone can provide support and PRs for resolving any macOS issues, I'll be happy to merge!

@paour Thank you, it will be the last resort if GitHub Actions is not working.

**Comment by tranxuanthang** [comment]
The v0.4.0 release now has both the build for x64 and Apple Silicon architectures:

https://github.com/tranxuanthang/lrcget/releases/tag/0.4.0
